FROM ruby:3.3.5

# Dependencias del sistema
RUN apt-get update -qq && apt-get install -y \
  build-essential \
  nodejs \
  postgresql-client \
  libpq-dev \
  git \
  curl

WORKDIR /app

# Gems primero (cache)
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Código de la app
COPY . .

EXPOSE 3000

CMD ["bash"]
